### PR TITLE
Login persistence

### PR DESCRIPTION
**Pull request by DanielGelfand-dev**
Implemented login persistence with logout functionality.

User registration functional.
User login functional.
User now posts questions/answers as themselves if logged in and as anonymous if logged out.

Modified UserController backend /login post method to allow for user login.

#20 #43 #73 #60

### CODE REVIEW

**Comment by Zlev1** [comment]
I think you might have pulled from my mistake branch, my files are good it's just the extra Js files that aren't the ones you changed are older

**Comment by DanielGelfand-dev** [comment]
Oh snap ok. Well  i didn't really use their functionality except the /login post method so we can re-merge the new branch with this one after it gets approved? I tested functionality and didn't see any errors with what we had before.

**Comment by Zlev1** [comment]
I think so what worries me is that this has a modified app.js which would mess up the other front end stuff pushed today. What I did on my end is only staged the files I added and changed but it seems merging this will be painful

**Comment by DanielGelfand-dev** [comment]
The other front end stuff wasn't pushed to main yet was it? I didn't touch the app.js so as long as it doesn't conflict with main we should be fine.

**Comment by Zlev1** [comment]
I guess they weren't @ArthurMoreDonuts might know but also Travis is failing on this one for some reason, we essentially need to fix the mess of these 3 pull requests, not now but tomorrow

**Comment by DanielGelfand-dev** [comment]
Yeah i have no idea why travis is failing, i'm currently running it on my end without any errors or compilation issues.

**Comment by Zlev1** [comment]
Also not sure why this one has no conflicts but the other does. I honestly don't know if it's a problem or not or git is just being weird

**Review by ArthurMoreDonuts — APPROVED** [review]
Tested on my side, works like a charm

**Review by Zlev1 — APPROVED** [review]
all is good i will fix the runtime errors on my backend code

**Pull request merged**
